name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pdf-generator:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/pdf-generator:latest
          cache-to: type=inline

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Enter the directory
            cd /home/${{ secrets.VM_USERNAME }}/pdf-generator

            # Pull in the repository
            git pull

            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/pdf-generator:latest

            # Stop and remove any old containers
            docker-compose down || true

            # Start the containers using Docker Compose
            docker-compose up -d --build

            # Remove all unused images and containers
            sudo docker system prune --all -f